name: 自动运行

on:
  schedule:
    # UTC时间每周三 18:30 运行，对应北京时间每周三 02:30
    - cron: '30 18 * * 3'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: 整合 uup
        run: .\auto-run.cmd uup
        shell: cmd

      - name: 上传 iso
        uses: actions/upload-artifact@v6
        with:
          name: iso
          path: "*.iso"

      - name: 制作 WinPE
        run: .\auto-run.cmd pe
        shell: cmd

      - name: 上传 wim
        uses: actions/upload-artifact@v6
        with:
          name: WinPE
          path: "*.wim"
